export const aboutMe = {
  name: "Jonasz",
  surname: "Jachym",
  mailAddress: "jajonaszjj@gmail.com",
  skills: [
    "React",
    "React Hooks",
    "Redux (Toolkit)",
    "Redux Saga",
    "React Router",
    "Git & GitHub",
    "JavaScript ES6+",
    "JSX",
    "NPM",
    "Semantic and accessible HTML",
    "Responsive Web Design",
    "Markdown",
    "CSS BEM convention",
    "CSS Flexbox & Grid",
    "Working with API (fetch, axios)",
    "Error Handling",
    "Scrum",
    "Trello & Jira",
    "Figma",
    "Photoshop & Illustrator",
    "Teamwork",
  ],
  toLearn: [
    "React Context",
    "Node.js",
    "Cypress",
    "Unit testing",
    "Typescript",
    "JS classes",
  ],
};
