export const skills = [
  "React",
  "React Hooks",
  "Redux (Toolkit)",
  "Redux Saga",
  "React Router",
  "Git & GitHub",
  "JavaScript ES6+",
  "NPM",
  "Semantic and accessible HTML",
  "Responsive Web Design",
  "Markdown",
  "CSS BEM convention",
  "CSS Flexbox",
  "CSS Grid",
  "Working with API (fetch, axios)",
  "Error Handling",
  "Scrum",
  "Trello",
  "Teamwork",
];

export const toLearn = [
  "React Context",
  "Node.js",
  "Cypress",
  "Unit testing",
  "Typescript",
  "JS classes",
];
